# SPDX-FileCopyrightText: 2022 Mikhail Zolotukhin <mail@gikari.com>
# SPDX-License-Identifier: MIT

name: Build plugin

on: [ push, pull_request ]

env:
  PLUGIN_NAME: QNVim
  QT_VERSION: 6.8.3
  CMAKE_VERSION: 4.1.2
  NINJA_VERSION: 1.13.1

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - {
            name: "Windows", artifact: "Windows-x64",
            os: windows-2022,
            cc: "cl", cxx: "cl",
          }
        - {
            name: "Linux", artifact: "Linux-x64",
            os: ubuntu-24.04,
            cc: "gcc-16", cxx: "g++-16"
          }
        - {
            name: "macOS", artifact: "macOS-x64",
            os: macos-14,
            cc: "clang", cxx: "clang++"
          }

    steps:
    - uses: actions/checkout@v5

    - name: Download Ninja and CMake
      run: cmake -P tools/ci/DownloadNinjaAndCMake.cmake

    - name: Install system libs
      run: cmake -P tools/ci/InstallSystemLibs.cmake

    - name: Install GCC 16
      if: matrix.config.os == 'ubuntu-24.04'
      run: |
        sudo apt update
        sudo apt install -y software-properties-common
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt update
        sudo apt install -y gcc-16 g++-16
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-16 100 --slave /usr/bin/g++ g++ /usr/bin/g++-16
        gcc --version; g++ --version

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{ env.QT_VERSION }}
        cache: true

    # To create a package, we need a script, that comes with Qt Creator
    # This is why we fetch it first, before invoking CMake
    - name: Download Qt Creator
      id: qt_creator
      run: cmake -P tools/DownloadQtCreator.cmake

    - name: Download Neovim
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: stable

    - name: Setup MSVC environment
      uses: ilammy/msvc-dev-cmd@v1
      if: ${{ matrix.config.cc == 'cl' }}

    - name: Build and Package
      run: cmake -P tools/ci/Package.cmake
      env:
        ARTIFACT_SUFFIX: ${{ matrix.config.artifact }}
        CC: ${{ matrix.config.cc }}
        CXX: ${{ matrix.config.cxx }}
        MACOSX_DEPLOYMENT_TARGET: "15.0"
        QT_DIR: ${{ env.Qt6_DIR }}/../../..
        QT_CREATOR_VERSION: ${{ steps.qt_creator.outputs.qtc_ver }}

    - uses: actions/upload-artifact@v5
      id: upload_artifact
      with:
        path: ./${{ env.PLUGIN_NAME }}-${{ steps.qt_creator.outputs.qtc_ver }}-${{ matrix.config.artifact }}.7z
        name: ${{ env.PLUGIN_NAME}}-${{ steps.qt_creator.outputs.qtc_ver }}-${{ matrix.config.artifact }}.7z
    outputs:
      qtc_ver: ${{ steps.qt_creator.outputs.qtc_ver }}

  release:
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Create Release
      id: create_release
      run: |
        gh release -R ${{ github.repository }} create ${{ github.ref_name }} -t "${{ env.NAME }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NAME: Release ${{ github.ref_name }}
    outputs:
      qtc_ver: ${{ needs.build.outputs.qtc_ver }}

  publish:
    if: contains(github.ref, 'tags/v')

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - {
            name: "Windows Latest x64", artifact: "Windows-x64.7z",
            os: ubuntu-latest
          }
        - {
            name: "Linux Latest x64", artifact: "Linux-x64.7z",
            os: ubuntu-latest
          }
        - {
            name: "macOS Latest x64", artifact: "macOS-x64.7z",
            os: macos-latest
          }
    needs: release

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v5
      with:
        name: ${{ env.PLUGIN_NAME }}-${{ needs.release.outputs.qtc_ver }}-${{ matrix.config.artifact }}
        path: ./

    - name: Upload to Release
      id: upload_to_release
      run: |
        gh release -R ${{ github.repository }} upload ${{ github.ref_name }} ${{ env.ASSET_PATH }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ASSET_PATH: ./${{ env.PLUGIN_NAME }}-${{ needs.release.outputs.qtc_ver }}-${{ matrix.config.artifact }}
